apiVersion: v1
kind: Service
metadata:
  name: processout-helloworld
  namespace: checkout
spec:
  selector:
    app: processout-helloworld
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
